import 'package:myfirstapp/part_requisition/main_home_part_requisition/part_requisition_all_file/part_requisition_data_model.dart';

List<PartRequisitionDataModel> partRequisitionDataList = [
  PartRequisitionDataModel(prNo: 'PR - 0001', status: 'PENDING', carCompany: 'Hyundai', carModel: 'i10', carFuel: 'Petrol', date: '14 JUN 2024 ', notes: 'I think i need my break pads changed and hear sound when i turn.', item_1: 'Air Filter ', item_2: 'Oil ', item_3: 'Oil filter '),
  PartRequisitionDataModel(prNo: 'PR - 0002', status: 'SUBMITTED', carCompany: 'Hyundai', carModel: 'i10', carFuel: 'Petrol', date: '14 JUN 2024 ', notes: 'I think i need my break pads changed and hear sound when i turn.', item_1: 'Air Filter', item_2: 'oil', item_3: 'Oil filter'),
  PartRequisitionDataModel(prNo: 'PR - 0003', status: 'PENDING', carCompany: 'Hyundai', carModel: 'i10', carFuel: 'Petrol', date: '14 JUN 2024 ', notes: 'I think i need my break pads changed and hear sound when i turn.', item_1: 'Air Filter', item_2: 'oil', item_3: 'Oil filter'),
  PartRequisitionDataModel(prNo: 'PR - 0004', status: 'SUBMITTED', carCompany: 'Hyundai', carModel: 'i10', carFuel: 'Petrol', date: '14 JUN 2024 ', notes: 'I think i need my break pads changed and hear sound when i turn.', item_1: 'Air Filter', item_2: 'oil', item_3: 'Oil filter'),
  PartRequisitionDataModel(prNo: 'PR - 0005', status: 'PENDING', carCompany: 'Hyundai', carModel: 'i10', carFuel: 'Petrol', date: '14 JUN 2024 ', notes: 'I think i need my break pads changed and hear sound when i turn.', item_1: 'Air Filter', item_2: 'oil', item_3: 'Oil filter'),
  PartRequisitionDataModel(prNo: 'PR - 0006', status: 'SUBMITTED', carCompany: 'Hyundai', carModel: 'i10', carFuel: 'Petrol', date: '14 JUN 2024 ', notes: 'I think i need my break pads changed and hear sound when i turn.', item_1: 'Air Filter', item_2: 'oil', item_3: 'Oil filter'),
  PartRequisitionDataModel(prNo: 'PR - 0007', status: 'SUBMITTED', carCompany: 'Hyundai', carModel: 'i10', carFuel: 'Petrol', date: '14 JUN 2024 ', notes: 'I think i need my break pads changed and hear sound when i turn.', item_1: 'Air Filter', item_2: 'oil', item_3: 'Oil filter'),
  PartRequisitionDataModel(prNo: 'PR - 0008', status: 'PENDING', carCompany: 'Hyundai', carModel: 'i10', carFuel: 'Petrol', date: '14 JUN 2024 ', notes: 'I think i need my break pads changed and hear sound when i turn.', item_1: 'Air Filter', item_2: 'oil', item_3: 'Oil filter'),
  PartRequisitionDataModel(prNo: 'PR - 0009', status: 'SUBMITTED', carCompany: 'Hyundai', carModel: 'i10', carFuel: 'Petrol', date: '14 JUN 2024 ', notes: 'I think i need my break pads changed and hear sound when i turn.', item_1: 'Air Filter', item_2: 'oil', item_3: 'Oil filter'),
];